### ISSUE TITLE
De-duplicate definitions

### ISSUE THREAD

**Issue by nicholascar** [surroundaustralia/Prez#10]
![image](https://user-images.githubusercontent.com/7321872/155695225-87a75c8a-b425-4c75-8d21-f3e64f6396db.png)

**Comment by jamiefeiss** [comment]
Do we want to keep the definition outside of the table under the title or have it only in the table as another prop?

Same goes for the instance URI

**Comment by nicholascar** [comment]
I think try above the table for both Description/Definition and IRI. They are standard properties and can have special places. The table’s really there to mop up all other properties

**Comment by jamiefeiss** [comment]
Resolved in f170faa.

Both the instance URI & description now sit above the table.
