### ISSUE TITLE
Empty results counting and listing collections

### ISSUE THREAD

**Issue by ldesousa** [surroundaustralia/Prez#104]
The queries used to count (`count_collections` method) and list collections (`list_collections` method) are returning 0 and empty for
the Floods knowledge graph. This is due to the following condition in the `WHERE` clause:

```
  ?d dcterms:identifier a dcat:Dataset 
             rdfs:member ?coll .
```

There are two issues with this formulation:

1. The profile does not define mandatory data properties with Dataset as domain and FeatureCollection as range. Even assuming the profile will eventually be updated (replacing `dcterms:isPartOf` for `rfds:member`), the mandatory data property with FeatureCollection as domain and Dataset as range should be used instead.

2. The `rdfs:member` data property declares the object as a member of the subject. Therefore its use with Dataset as domain and FeatureCollection as range is semantically inconsistent with the RDFS ontology.

**Comment by recalcitrantsupplant** [comment]
Hi Luis, my understanding of rdfs:member has the object as a member of the subject. I've checked the RDFS ontology and it doesn't clarify this point for me. Are you able to point me to something definitive here?

**Comment by ldesousa** [comment]
Hi David, the semantics of the `rfds:member` data property is defined in [Section 6.2](https://www.w3.org/TR/rdf-schema/#ch_sumproperties) as:
> A member of the subject resource.

This triple:
```
:a rdfs:member :b
```
Translates to natural language:
> B is member of A.

or:
> A has member B.

So the triple `:dataset rfds:member :collection` would be correct. Appologies for the confusion.

Are you planning to update the profile? Without it feels like I am flying bind :)

**Comment by recalcitrantsupplant** [comment]
Hi Luis, I've updated it just now.
