### ISSUE TITLE
Render xsd:anyURI as hyperlinks

### ISSUE THREAD

**Issue by nicholascar** [surroundaustralia/Prez#11]
The literal `xsd:anyURI` is used for hyperlinks that are not nodes n the RDF graph, e.g. just links to web pages. In HTML, they should be rendered as hyperlinks, not text:

![image](https://user-images.githubusercontent.com/7321872/155731078-e1c18625-04a5-419a-b230-13e6c6e83bed.png)

**Comment by recalcitrantsupplant** [comment]
confirmed working in latest prez
