### ISSUE TITLE
Concept search not working

### ISSUE THREAD

**Issue by recalcitrantsupplant** [surroundaustralia/Prez#110]
May be specific to combined VocPrez/SpacePrez instances

e.g. here: https://linked.fsdf.org.au/search

**Comment by tina5870** [comment]
If searching concepts, always quickly get 'Internal Server Error' very quickly. for example, https://linked.fsdf.org.au/search?search=cage&endpoints=self

**Comment by nicholascar** [comment]
See https://github.com/RDFLib/prez/issues/7
