### ISSUE TITLE
Search performance

### ISSUE THREAD

**Issue by recalcitrantsupplant** [surroundaustralia/Prez#112]
Catch all issue for search performance issues. If specific things are found that do not work they can be noted here

Placename dataset search gets 'Internal Server Error' https://gajira.atlassian.net/browse/DAP-229 (private link)

**Comment by recalcitrantsupplant** [comment]
placenames

**Comment by nicholascar** [comment]
Closing this catch-all in favour of the individual search issues in https://github.com/RDFLib/prez/issues for when they are resolved, we will need to evidence other specific search issues to address them.
