### ISSUE TITLE
documentation not found

### ISSUE THREAD

**Issue by rapw3k** [surroundaustralia/Prez#113]
Hi 
can you please check documentation link: https://surroundaustralia.github.io/Prez/ 
Currently is not found
thanks!
Raul

**Comment by recalcitrantsupplant** [comment]
Hi Raul, looks like we intended to use github pages for documentation but didn't finish implementing it - I've made an update to the readme (pending a PR https://github.com/surroundaustralia/Prez/pull/115) with some instructions on different ways to run Prez. Let me know if you have any issues.
