### ISSUE TITLE
the feature geometry expand button is a bit strange in the power station and transmission line feature collections

### ISSUE THREAD

**Issue by tina5870** [surroundaustralia/Prez#116]
![feature_geometry_expand_problem](https://user-images.githubusercontent.com/5643889/182290314-b0b6a794-519b-4ea9-af5f-606b83ba6b30.JPG)

When mouse hovering on the Expand button in a feature's geometry part, the button is only activated by hovering on the left corner of the button instead of anywhere on the button

As tested, this problem only happens to the power station and transmission line feature collections.

**Comment by nicholascar** [comment]
See https://github.com/RDFLib/prez/issues/11
