### ISSUE TITLE
Shrink large coordinate literals

### ISSUE THREAD

**Issue by nicholascar** [surroundaustralia/Prez#12]
Large coordinate literals in the original OGC LD API where visually reduced with an ellipsis, see http://floods.surroundaustralia.com/collections/HF2021/items/1003. This needs to be implemented again. If possible, a click-to-copy button or a way to get the entire set of coordinates would be good too.

**Comment by jamiefeiss** [comment]
Resolved in f3af654.

Implemented a copy button & an expand/collapse button. 
![image](https://user-images.githubusercontent.com/58060490/164373184-d0fddd8d-ea52-4c2c-ab7e-423ba81c11b8.png)
