### ISSUE TITLE
rdfs:member

### ISSUE THREAD

**Issue by recalcitrantsupplant** [surroundaustralia/Prez#13]
https://github.com/surroundaustralia/Prez/blob/ad2f9fe73d548468918d63765db7511f96673081/prez/services/spaceprez_service.py#L200

Do we know where rdfs:member came from? It may well be part of the OGC spec but I can't find it. Currently my features / fcs / datasets are all linked by dcterms:isPartOf only, so this SPARQL query is returning nothing and giving me a 404 on ...collections/{collection}

**Comment by nicholascar** [comment]
`rdfs:member` is now the required property to be used to link `SpatialObjectCollection` to `SpatialObject` (and subclass equivalents) in GeoSPARQL 1.1.
