### ISSUE TITLE
SPARQL_ENDPOINT as environment variable

### ISSUE THREAD

**Issue by recalcitrantsupplant** [surroundaustralia/Prez#14]
https://github.com/surroundaustralia/Prez/blob/ad2f9fe73d548468918d63765db7511f96673081/prez/config.py#L44

Could we please remove the nesting / json to simplify configuration - either altogether, or if we think there are current use cases for multiple prez types on one instance, then with differently named environment variables relating to the type.

**Comment by jamiefeiss** [comment]
Resolved in f3af654.
