### ISSUE TITLE
Create GH action to build / push image to dockerhub

### ISSUE THREAD

**Issue by recalcitrantsupplant** [surroundaustralia/Prez#15]
NB the current images on dockerhub do not have the 'latest' tag so `docker pull surroundaustralia/prez:latest` does not work - could we please ensure the latest image is pulled

**Comment by jamiefeiss** [comment]
Implemented in 4353fd8.

I've also added some branch restrictions to enforce using approved PRs for feature/* -> main.

The actions are:
- Pushes to feature/* run tests (placeholder for now)
- Opened PRs from feature/* to main run integration tests (placeholder for now)
- Pushes to main push :latest to Docker Hub
- Creating a GitHub release pushes the versioned tag (the patch, minor & major versions) to Docker Hub (versioning should follow e.g. v0.1.2)
