### ISSUE TITLE
Display Custom Datatypes

### ISSUE THREAD

**Issue by nicholascar** [surroundaustralia/Prez#17]
The objects for `skos:notation` often have custom datatypes and, currently, Prez doesn't show these. E.g.:

http://vocabs.stratigraphy.org/vocab/chart/Burdigalian

The values:  
Notation #FFFF41, 255/255/65, 0/0/75/0

have the following RDF:

```turtle
isc:Burdigalian
  a skos:Concept ;
  dcterms:identifier "Burdigalian" ;
  skos:definition "Colour for Burdigalian" ;
  skos:notation "#FFFF41"^^:RGBHex ;
  skos:notation "0/0/75/0"^^:CMYK ;
  skos:notation "255/255/65"^^:RGB ;
  skos:prefLabel "Burdigalian"@en ;
  skos:topConceptOf cs: ;
  skos:inScheme cs: ;
.
```

with:

```turtle
:CMYK
  a owl:Datatype ;
  dcterms:description """..."""@en ;
  dcterms:source <https://en.wikipedia.org/wiki/CMYK_colour_model> ;
  dcterms:title "CMYK colour model" ;
.
:RGB
  a owl:Datatype ;
  dcterms:description """..."""@en ;
  dcterms:source <https://en.wikipedia.org/wiki/RGB_colour_model> ;
  dcterms:title "CMYK colour notation" ;
.
:RGBHex
  a owl:Datatype ;
  dcterms:description """..."""@en ;
  dcterms:title "CMYK colour notation" ;
.
```

So the datatypes are defined and have labels. The Labels could be changes to RDFS or SKOS, rather than DCTERMS, if that helps.

It would be good to have the prefixed IRI or the label displayed after the value to indicate the specialised type.

**Comment by recalcitrantsupplant** [comment]
completed using carets in prez
