### ISSUE TITLE
Name not found in connegp module

### ISSUE THREAD

**Issue by ldesousa** [surroundaustralia/Prez#28]
I am trying to run Prez on Ubuntu 20.04 with Python 3.8.10. I checked out the repository, set up a virtual environment, installed poetry and the requirements. Once I tried running the application, Python complained that `connegp` was missing:

```
$ python3 app.py
Traceback (most recent call last):
  File "app.py", line 12, in <module>
    from connegp import parse_mediatypes_from_accept_header
ModuleNotFoundError: No module named 'connegp'
```

I thus installed the package a gave it another go:

```
$ pip3 install connegp
/home/duque004/git/Prez/env/lib/python3.8/site-packages/secretstorage/util.py:46: UserWarning: Passing unwrap= to .send_and_get_reply() is deprecated and will break in a future version of Jeepney.
  return self._connection.send_and_get_reply(msg, unwrap=True)
Collecting connegp
  Downloading connegp-0.2-py3-none-any.whl (15 kB)
Installing collected packages: connegp
Successfully installed connegp-0.2

$ python3 app.py
Traceback (most recent call last):
  File "app.py", line 12, in <module>
    from connegp import parse_mediatypes_from_accept_header
ImportError: cannot import name 'parse_mediatypes_from_accept_header' from 'connegp' (/home/duque004/git/Prez/env/lib/python3.8/site-packages/connegp/__init__.py)
```

Checking the `connegp` repository, it looks like the name `parse_mediatypes_from_accept_header` never existed. Perhaps it is necessary to push a new version to GitHub and PyPi?

**Comment by recalcitrantsupplant** [comment]
Can you please retest with the latest version (0.2.1+) - we think a incorrect dependency was updated some time ago as we've been running 'new' copies of the API without issue.

**Comment by sgrellet** [comment]
Bonjour Everyone,
Currently in the process of testing Prez for EPOS EU Research Infrastructure.
We are having the exact same problem here.
But looking at https://pypi.org/project/connegp/ we only see 0.2 thus cannot retest.
Are we missing something ?
@cfollenf feel free to add more description

**Comment by recalcitrantsupplant** [comment]
Gday!
I've updated the requirements.txt, it was pointing to an old version of ConnegP. I don't believe the newer version has been packaged and put on PyPi. We're actually using poetry (https://python-poetry.org/), which uses the pyproject.toml rather than requirements.txt, which is why this had been missed. I'd highly recommend poetry as it prevents a lot of dependency issues.
One of my colleagues should approve/merge the change soon, or you can try the branch in the interim.

**Comment by ldesousa** [comment]
Just tested again with 325043e5fa6088a027cbd2100a33494facc3febd, the same behaviour prevails.

**Comment by cfollenf** [comment]
Having tested with https://github.com/surroundaustralia/Prez/commit/7175f78591d52679a4623367ec335efb069dd8e4 poetry didn't change my local deployment, but updating pip with the new requirements fixed the problem and made running Prez possible by fetching the ConnegP2 instead of ConnegP.
Thanks!

**Comment by recalcitrantsupplant** [comment]
Yes, assuming the package names being the same and versions (or lack of versioning) has meant the old package was found
