### ISSUE TITLE
Should swagger display additional mediatypes

### ISSUE THREAD

**Issue by recalcitrantsupplant** [surroundaustralia/Prez#30]
As per title, assume it should, currently only application/json is getting picked up in the dropdown, e.g. here:

http://da-ap-loadb-12x6lrd462qbh-6729920eb84d632c.elb.ap-southeast-2.amazonaws.com:8000/docs#/default/sparql_get_sparql_get

**Comment by nicholascar** [comment]
See https://github.com/RDFLib/prez/issues/3
