### ISSUE TITLE
Use SHACL to control  nested object details

### ISSUE THREAD

**Issue by rob-metalinkage** [surroundaustralia/Prez#32]
Using SHACL and DASH (https://datashapes.org/dash) we can specify the set of properties a profile of an object should expose in PREZ.

A nested object uses a shape defined by sh:node on the nesting property

tdisp:Sample-observation-inverse
 a sh:PropertyShape ;
  sh:path [ sh:inversePath sosa:hasFeatureOfInterest ] ;
  sh:node tdisp:ObsMinimal ;
.

tdisp:ObsMinimal a sh:NodeShape ;
	rdfs:label "Minimal Observations Shape" ;
	sh:targetClass tern:Observation ;
	rdfs:comment "Highlights whats actually been sampled" ;
	sh:property tern-shapes:sosa-observedProperty,
       tern-shapes:Observation-hasResult ;
.

So we can use this to define, for a given object type its nested object profiles.

If a single property is defined for such a shape, then the JINJA template can suppress the nested object's subproperty label.

**Comment by recalcitrantsupplant** [comment]
we will use flat lists of predicates to control what is displayed for different profiles. Any more complicated logic will need to be built out in the data.
