### ISSUE TITLE
Allow SPARQL endpoint do be selected in YASGUI

### ISSUE THREAD

**Issue by recalcitrantsupplant** [surroundaustralia/Prez#48]
Ideally from a predefined list i.e. those SPARQL endpoints which the API is set up to query

NB I think the existing SPARQL endpoint selector can be enabled in index.css by commenting out (or editing) the following:
```
#yasgui .autocompleteWrapper {
  display: none !important;
}
```

**Comment by recalcitrantsupplant** [comment]
For cases where more than one Prez type is running e.g. spaceprez + vocprez

**Comment by nicholascar** [comment]
See https://github.com/RDFLib/prez/issues/4
