### ISSUE TITLE
Quick Links for Alt Profiles broken

### ISSUE THREAD

**Issue by nicholascar** [surroundaustralia/Prez#60]
Many of the "Quick Links for Alt Profiles" links are not working in both SpacePrez & VocPrez and there are random profiles listed like "OGC Linked" & "Profiles" which shouldn't be there.

The base for all the quick links should be the system URL - the page we are on - or the PID IRI of the object on the page. The choice between system URL and PID IRI should be configurable in settings.

We need to audit the "Quick Links for Alt Profiles" and the Alt Profiles page per endpoint in VP & SP to ensure that the correct Profiles and formats are made per endpoint.

* /
* /vocprez
    * /vocab
    * /vocab/{VOCAB-X}
    * /vocab/{VOCAB-X}/{CONCEPT-Y}
    * /collection
    * /collection/{COLLECTION-Z}
* /spaceprez
    * /datasets
    * /dataset/{DATASET-X}
    * /dataset/{DATASET-X}/collections
    * /dataset/{DATASET-X}/collections/{COLLECTION-Y}
    * /dataset/{DATASET-X}/collections/{COLLECTION-Y}/items
    * /dataset/{DATASET-X}/collections/{COLLECTION-Y}/items/{FAETURE-Z}

And test for a standard SpacePrez (e.g. ASGS) and a more customied one (e.g. GA Samples)

**Comment by recalcitrantsupplant** [comment]
"The base for all the quick links should be the system URL" I've fixed this (locally!).
I've got the correct profiles for a feature. Will apply the same style to FeatureCollection and Dataset, then the rest should be more straightforward. I'll commit where I'm at to a branch on Monday.

**Comment by nicholascar** [comment]
Long since fixed...
