### ISSUE TITLE
Using geof:sfWithin() causes a 500 error

### ISSUE THREAD

**Issue by nicholascar** [surroundaustralia/Prez#68]
When I try the following query, I get a 500 error:

```
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?f
WHERE {
    <https://linked.data.gov.au/dataset/asgsed3/SA4/102> geo:hasGeometry/geo:asWKT ?container .

    <https://linked.data.gov.au/dataset/asgsed3/SA3> rdfs:member ?f .
    ?f geo:hasGeometry/geo:asWKT ?wkt .

    FILTER (geof:sfWithin(?container, ?wkt))
}
LIMIT 5   
```

This is a standard GeoSPARQL query so should work.

To get around the HTTPS problem listed in Issue #66, I'm POSTing the above query to ASGS Prez using this Jupyer notebook:

https://github.com/surroundaustralia/daa-api-clients/blob/master/notebooks/IderDown.ipynb

**Comment by recalcitrantsupplant** [comment]
API gives 504 timeout. The SA4 Polygons are very large - indexing doesn't seem to have helped here.
We'll add some more resources to the API.

Probably best to use the actual SPARQL endpoint as below until #66 is resolved.
Your geof:sfWithin should be FILTER (geof:sfWithin(?wkt, ?container))

Example working query using SA1s / an SA2:

http://digital-atlas-lb-1849576075.ap-southeast-2.elb.amazonaws.com:3060/#/dataset/fsdf/query?query=PREFIX%20geo%3A%20%3Chttp%3A%2F%2Fwww.opengis.net%2Font%2Fgeosparql%23%3E%0APREFIX%20geof%3A%20%3Chttp%3A%2F%2Fwww.opengis.net%2Fdef%2Ffunction%2Fgeosparql%2F%3E%0APREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0A%0ASELECT%20%3Ff%0AWHERE%20%7B%0A%20%20%20%20%3Chttps%3A%2F%2Flinked.data.gov.au%2Fdataset%2Fasgsed3%2FSA2%2F101021007%3E%20geo%3AhasGeometry%2Fgeo%3AasWKT%20%3Fcontainer%20.%0A%0A%20%20%20%20%3Chttps%3A%2F%2Flinked.data.gov.au%2Fdataset%2Fasgsed3%2FSA1%3E%20rdfs%3Amember%20%3Ff%20.%0A%20%20%20%20%3Ff%20geo%3AhasGeometry%2Fgeo%3AasWKT%20%3Fwkt%20.%0A%0A%20%20%20%20FILTER%20%28geof%3AsfWithin%28%3Fwkt%2C%20%3Fcontainer%29%29%0A%20%20%09%0A%7D%0ALIMIT%205

**Comment by recalcitrantsupplant** [comment]
@adamdavis2 please increase ASGS API resources for fuseki - memory and cpu

**Comment by recalcitrantsupplant** [comment]
@nicholascar please advise if issue has been resolved

**Comment by nicholascar** [comment]
Just tried at https://asgs.linked.fsdf.org.au/sparql but still getting zero results.

Just tried with reversed `?container` & ?`wkt` as but still zero.

The container should be the second function input as per https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#C.2.2.2.

```
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?f
WHERE {
    <https://linked.data.gov.au/dataset/asgsed3/SA4/102> geo:hasGeometry/geo:asWKT ?container .

    <https://linked.data.gov.au/dataset/asgsed3/SA3> rdfs:member ?f .
    ?f geo:hasGeometry/geo:asWKT ?wkt .

    FILTER (geof:sfWithin(?wkt, ?container))
}
LIMIT 5  
```

**Comment by recalcitrantsupplant** [comment]
Set limit to 1 does not timeout for me, returns 1 result in 11 seconds. Limit 5 returns 2 results in 27 seconds, which is getting close to the 30s timeout. Expect better performance with smaller polygons - haven't extensively tested

**Comment by recalcitrantsupplant** [comment]
@nicholascar index enabled - above results are now 5 seconds and 7 seconds respectively.

Repeating the same query, time is 1 second. Didn't realise there was a cache, but there must be.

Also fyi @adamdavis2
