### ISSUE TITLE
Ensure English, or selected language, prefLabel is selected for oncept/Vocab etc

### ISSUE THREAD

**Issue by nicholascar** [surroundaustralia/Prez#7]
![image](https://user-images.githubusercontent.com/7321872/155694370-f6f17a55-40a6-4e96-a1bc-28ba6822222c.png)

Here the Italian PL is used as the page title but it should be English (or system lang)

**Comment by jamiefeiss** [comment]
Resolved in f170faa.

For now I've added some filters to the SPARQL query to filter by either English language tag or no language tag.

In the future we should implement a "system language" config to change the above query.
