### ISSUE TITLE
Add startup feature count

### ISSUE THREAD

**Issue by recalcitrantsupplant** [surroundaustralia/Prez#89]
Add prez:count triple on start up for count of features in feature collections *if* it doesn't already exist.

```
PREFIX prez: <https://surroundaustralia.com/prez/>
INSERT DATA {GRAPH prez:metadata {<feature_collection> prez:count ?count}}
WHERE (COUNT(?f) as ?count) SELECT ....
```

This will get picked up by the current feature count python function, which first checks for a prez:count, and otherwise counts features using a regular SPARQL count

**Comment by nicholascar** [comment]
Is this complete?

**Comment by recalcitrantsupplant** [comment]
Prez will look for feature collection counts using a query of the form
`GRAPH prez:metadata {<feature_collection> prez:count ?count`
If no results are returned then a SPARQL query will be used to count features. This SPARQL query is expensive for large datasets. Therefore for large datasets it is recommended to determine a count of the features 'offline' and add a triple of the above form, such that no 'online' counting is required (for example, if using Apache Jena, using tdb2.tdbupdate).
