### ISSUE TITLE
404 error accessing dataset pages

### ISSUE THREAD

**Issue by ldesousa** [surroundaustralia/Prez#95]
The dataset pages are all returning 404 errors in my local Prez instance. In the example below I have two datasets compliant with the ocgldapi profile, including the *Floods* dataset from SpacePrez:

![Prez02](https://user-images.githubusercontent.com/1137878/175940911-16080525-8669-472d-8a63-b3f5a09de934.png)

This is the result whenever I try to access a dataset page:

![Prez01](https://user-images.githubusercontent.com/1137878/175941054-2aab8bf3-5282-4d19-b234-a8e07b5274e5.png)

In the log (`prez.log`) there are things like:

```
INFO:     127.0.0.1:46266 - "GET /datasets HTTP/1.1" 200 OK
INFO:     127.0.0.1:46268 - "GET /dataset/floods HTTP/1.1" 404 Not Found
```

Is there any other point of logging that could help investigating this further?

**Comment by recalcitrantsupplant** [comment]
Hi Luis, do you mind confirming the version you're running, and if not the latest (0.3.10) could you retry with that one. There were a few bugs identified in the past few days that the test suite didn't pick up, which have now been rectified. If that doesn't solve the issue, I assume the SPARQL query for the floods endpoint is not getting all of the data the renderer requires. You could confirm this by placing a breakpoint in the dataset endpoint function (currently line 222 of prez/routers/spaceprez_router.py) and confirming the `sparql_result` has something sensible. We could improve the code by raising errors at this point rather than trying to render an empty result set.

**Comment by ldesousa** [comment]
Thank you for the swift reply, here is what I found so far using release v0.3.10. The query failling is created in the `get_dataset_construct` method of the `spaceprez_service.py` module. For the Floods dataset this query is:

```
        PREFIX dcat: <http://www.w3.org/ns/dcat#>
        PREFIX dcterms: <http://purl.org/dc/terms/>
        PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
        PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
        CONSTRUCT {
            ?d ?p1 ?o1 ;
                rdfs:member ?coll .
            ?coll dcterms:identifier ?coll_id ;
                dcterms:title ?coll_title .

?p1 rdfs:label ?p1Label ;
    dcterms:description ?p1def ;
    dcterms:provenance ?p1expl .
?o1 rdfs:label ?o1Label ;
    dcterms:description ?o1def .


?o1 ?p2 ?o2 .
?p2 rdfs:label ?p2Label ;
    dcterms:description ?p2def ;
    dcterms:provenance ?p2expl .
?o2 rdfs:label ?o2Label ;
    dcterms:description ?o2def .

        }
        WHERE {

        ?d dcterms:identifier "floods"^^xsd:token ;
            a dcat:Dataset .
        BIND("floods" AS ?id)

            ?d ?p1 ?o1 ;
                rdfs:member ?coll .
            ?coll dcterms:identifier ?coll_id ;
                dcterms:title ?coll_title .

OPTIONAL {
    ?o1 ?p2 ?o2 .
    FILTER(ISBLANK(?o1))

    OPTIONAL {
        ?p2 rdfs:label|dcterms:title ?p2Label .
        FILTER(lang(?p2Label) = "" || lang(?p2Label) = "en")
    }
    OPTIONAL {
        ?p2 dcterms:description ?p2def .
        FILTER(lang(?p2def) = "" || lang(?p2def) = "en")
    }
    OPTIONAL {
        ?p2 dcterms:provenance ?p2expl .
        FILTER(lang(?p2expl) = "" || lang(?p2expl) = "en")
    }
    OPTIONAL {
        ?o2 rdfs:label|dcterms:title ?o2Label .
        FILTER(lang(?o2Label) = "" || lang(?o2Label) = "en")
    }
    OPTIONAL {
        ?o2 dcterms:description ?o2def .
        FILTER(lang(?o2def) = "" || lang(?o2def) = "en")
    }
}


OPTIONAL {
    ?p1 rdfs:label|dcterms:title ?p1Label .
    FILTER(lang(?p1Label) = "" || lang(?p1Label) = "en")
}
OPTIONAL {
    ?p1 dcterms:description ?p1def .
    FILTER(lang(?p1def) = "" || lang(?p1def) = "en")
}
OPTIONAL {
    ?p1 dcterms:provenance ?p1expl .
    FILTER(lang(?p1expl) = "" || lang(?p1expl) = "en")
}
OPTIONAL {
    ?o1 rdfs:label|dcterms:title ?o1Label .
    FILTER(lang(?o1Label) = "" || lang(?o1Label) = "en")
}
OPTIONAL {
    ?o1 dcterms:description ?o1def .
    FILTER(lang(?o1def) = "" || lang(?o1def) = "en")
}

        }
``` 

This query returns zero records and forces the 404 error message. It is somewhat deep, so I chopped it off in smaller bits. First, the dataset matching by name is functional:

```
SQL> SPARQL
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?d
WHERE {

?d dcterms:identifier "floods"^^xsd:token ;
    a dcat:Dataset .
};
Type the rest of statement, end with a semicolon (;)> Type the rest of statement, end with a semicolon (;)> Type the rest of statement, end with a semicolon (;)> Type the rest of statement, end with a semicolon (;)> Type the rest of statement, end with a semicolon (;)> Type the rest of statement, end with a semicolon (;)> Type the rest of statement, end with a semicolon (;)> Type the rest of statement, end with a semicolon (;)> Type the rest of statement, end with a semicolon (;)> Type the rest of statement, end with a semicolon (;)> d
LONG VARCHAR
_______________________________________________________________________________

https://linked.data.gov.au/dataset/floods

1 Rows. -- 1 msec.
```

However, once I add in the matching pattern with `rdfs:member` it falls appart:

```
SQL> SPARQL
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?d ?coll
WHERE {

?d dcterms:identifier "floods"^^xsd:token ;
    a dcat:Dataset .

?d ?p1 ?o1 ;
    rdfs:member ?coll .
};
Type the rest of statement, end with a semicolon (;)> Type the rest of statement, end with a semicolon (;)> Type the rest of statement, end with a semicolon (;)> Type the rest of statement, end with a semicolon (;)> Type the rest of statement, end with a semicolon (;)> Type the rest of statement, end with a semicolon (;)> Type the rest of statement, end with a semicolon (;)> Type the rest of statement, end with a semicolon (;)> Type the rest of statement, end with a semicolon (;)> Type the rest of statement, end with a semicolon (;)> Type the rest of statement, end with a semicolon (;)> Type the rest of statement, end with a semicolon (;)> Type the rest of statement, end with a semicolon (;)> d                                                                                 coll
LONG VARCHAR                                                                      LONG VARCHAR
_______________________________________________________________________________


0 Rows. -- 11 msec.
```

In fact, the `rdfs:member` predicate is never used in the dataset:

```
$ grep rdfs:member floods.ttl
$ grep member floods.ttl
$
```  

This predicate is not mention in the [ogcldapi-profile](https://github.com/surroundaustralia/ogcldapi-profile/blob/master/specification.md) either. If I understand it correctly, this query should be using the `dcterms:isPartOf` predicate instead, but would like to hear your reasoning before starting to tinker.

**Comment by ldesousa** [comment]
Hello again. Could you provide some reaction to this issue? Do you see it as something on the side of the service or on the side of the dataset? In the latter case, what are your intentions regarding the ogcldapi profile? Thanks.

**Comment by recalcitrantsupplant** [comment]
Hey Luis, sorry for the delay, I saw your message and forgot to come back to this. Yes the API now uses rdfs:member rather than dcterms:hasPart, and the profile should be updated accordingly (you can of course use both properties together should you wish). I can't recall the reasoning - I've asked Nick to respond to this.

Where did you get the floods dataset from? I am familiar with it but that's likely an old version.

One of the major recent changes to Prez was a lot of unit tests. As part of this two smaller datasets were included. Nick also added functionality to run a local mock SPARQL endpoint in Python, using RDFLib. With these changes you can run a "demo" version of Prez using the test data as follows:

1. Run the SPARQL store: `python tests/local_sparql_store/store.py`
2. Set the following environment variables for Prez:
```
ENABLED_PREZS=["SpacePrez", "VocPrez"]
SPACEPREZ_SPARQL_ENDPOINT=http://localhost:3030/spaceprez
VOCPREZ_SPARQL_ENDPOINT=http://localhost:3030/vocprez
```
4. Run Prez: `python prez/app.py`

**Comment by nicholascar** [comment]
> the API now uses rdfs:member rather than dcterms:hasPart, and the profile should be updated accordingly

The reason for this change is that the GeoSPARQL standard adopted `rdfs:member` and we are just following that.

It's good to be cutting-edge with the standard implementation but then we do get update issues like this!

**Comment by ldesousa** [comment]
@recalcitrantsupplant As referred in the first message, this is [the dataset](https://github.com/surroundaustralia/surround-prez-features/blob/main/data/floods.ttl) in the latest commit to SpacePrez. 

@nicholascar Thank you for clarifying. It would be important to keep the profile up to date. It is one of the most important assets in this constellation you are building.

**Comment by ldesousa** [comment]
After some thought, my suggestion here is to adapt the query to work with both membership predicates. The profile relies exclusively on the DCTerms, and I think that to be the soundest option semantically.

**Comment by ldesousa** [comment]
I just created a pull request updating the Floods knowledge graph:
https://github.com/surroundaustralia/surround-prez-features/pull/2

**Comment by recalcitrantsupplant** [comment]
Thanks Luis, @jamiefeiss will update or remove the dataset from surround-prez-features.
